export default {
	1:"Adelphi University",
	2:"Agnes Scott College",
	3:"Alabama A&M",
	4:"Allegheny College",
	5:"American International College",
	6:"American University",
	7:"Amherst College",
	8:"Andrews University",
	9:"Appalachian State University",
	10:"Arizona State University - Tempe",
	11:"Art Center College of Design",
	12:"Ashland University",
	13:"Auburn University",
	14:"Augusta University",
	15:"Augustana College",
	16:"Augustana University",
	17:"Austin College",
	18:"Azusa Pacific University",
	19:"Ball State University",
	20:"Bard College",
	21:"Barnard College",
	22:"Barry University",
	23:"Bates College",
	24:"Baylor University",
	25:"Bellarmine University",
	26:"Belmont Abbey College",
	27:"Belmont University",
	28:"Beloit College",
	58:"Carleton College",
	29:"Benedictine University",
	30:"Bennett College",
	31:"Bennington College",
	32:"Bentley University",
	33:"Berry College",
	34:"Biola University",
	35:"Blue Mountain College",
	36:"Boise State University",
	37:"Boston College",
	38:"Boston University",
	39:"Bowdoin College",
	40:"Bowling Green State University",
	41:"Bradley University",
	42:"Brandeis University",
	43:"Brigham Young University - Provo",
	44:"Brown University",
	45:"Bryant University",
	46:"Bryn Mawr College",
	47:"Bucknell University",
	48:"Butler University",
	49:"CUNY - Baruch College",
	50:"California Institute of Technology",
	51:"California Institute of the Arts",
	52:"California Polytechnic State University - San Luis Obispo",
	53:"California State Polytechnic University - Pomona",
	54:"California State University - Fresno",
	55:"California State University - Fullerton",
	56:"Calvin College",
	57:"Cardinal Stritch University",
	59:"Carnegie Mellon University",
	60:"Carroll College",
	61:"Case Western Reserve University",
	62:"Catawba College",
	63:"Catholic University of America",
	64:"Cazenovia College",
	65:"Cedar Crest College",
	66:"Central Michigan University",
	67:"Centre College",
	68:"Chapman University",
	69:"City College of New York",
	70:"Claflin University",
	71:"Claremont McKenna College",
	72:"Clark Atlanta University",
	73:"Clark University",
	74:"Clarkson University",
	75:"Clemson University",
	76:"Cleveland State University",
	77:"Coe College",
	78:"Coker College",
	79:"Colby College",
	80:"Colgate University",
	81:"College of Charleston",
	82:"College of New Jersey",
	83:"College of St. Benedict",
	84:"College of William & Mary",
	85:"College of Wooster",
	86:"College of the Atlantic",
	87:"College of the Holy Cross",
	117:"Edgewood College",
	88:"College of the Ozarks",
	89:"Colorado College",
	90:"Colorado School of Mines",
	91:"Colorado State University",
	92:"Columbia University",
	93:"Concordia College - Moorhead",
	94:"Connecticut College",
	95:"Cooper Union",
	96:"Cornell College",
	97:"Cornell University",
	98:"Creighton University",
	99:"Dallas Baptist University",
	100:"Dartmouth College",
	101:"Davidson College",
	102:"DePaul University",
	103:"DePauw University",
	104:"Denison University",
	105:"Dickinson College",
	106:"Dillard University",
	107:"Dordt College",
	108:"Drake University",
	109:"Drew University",
	110:"Drexel University",
	111:"Duke University",
	112:"Duquesne University",
	113:"Earlham College",
	114:"East Carolina University",
	115:"East Tennessee State University",
	116:"Eastern Michigan University",
	118:"Elizabethtown College",
	119:"Elmhurst College",
	120:"Elon University",
	121:"Embry-Riddle Aeronautical University",
	122:"Emerson College",
	123:"Emory University",
	124:"Fairfield University",
	125:"Fayetteville State University",
	126:"Fisk University",
	127:"Flagler College",
	128:"Florida A&M University",
	129:"Florida Atlantic University",
	130:"Florida Institute of Technology",
	131:"Florida International University",
	132:"Florida State University",
	133:"Fordham University",
	134:"Franklin W. Olin College of Engineering",
	135:"Franklin and Marshall College",
	136:"Furman University",
	137:"Gallaudet University",
	138:"Gardner-Webb University",
	139:"George Mason University",
	140:"George Washington University",
	141:"Georgetown University",
	142:"Georgia Institute of Technology",
	143:"Georgia Southern University",
	144:"Georgia State University",
	145:"Gettysburg College",
	146:"Gonzaga University",
	147:"Goshen College",
	148:"Goucher College",
	149:"Grand Canyon University",
	150:"Grinnell College",
	151:"Gustavus Adolphus College",
	152:"Hamilton College",
	153:"Hampden-Sydney College",
	154:"Hampton University",
	155:"Harvard University",
	156:"Harvey Mudd College",
	157:"Haverford College",
	159:"Hendrix College",
	160:"High Point University",
	161:"Hillsdale College",
	162:"Hobart and William Smith Colleges",
	163:"Hofstra University",
	164:"Hollins University",
	165:"Hope College",
	166:"Howard Payne University",
	167:"Howard University",
	168:"Huntingdon College",
	169:"Illinois Institute of Technology",
	170:"Illinois State University",
	171:"Illinois Wesleyan University",
	172:"Immaculata University",
	173:"Indiana State University",
	174:"Indiana University - Bloomington",
	175:"Indiana University of Pennsylvania",
	176:"Indiana University-Purdue University - Indianapolis",
	177:"Iowa State University",
	178:"Ithaca College",
	179:"Jackson State University",
	180:"James Madison University",
	181:"John Carroll University",
	182:"Johns Hopkins University",
	183:"Juniata College",
	184:"Kalamazoo College",
	185:"Kansas State University",
	186:"Kennesaw State University",
	187:"Kent State University",
	188:"Kenyon College",
	189:"Kettering University",
	190:"Knox College",
	191:"Lafayette College",
	192:"Lake Forest College",
	193:"Lamar University",
	194:"Lawrence University",
	195:"Le Moyne College",
	196:"Lehigh University",
	197:"Lesley University",
	198:"Lewis & Clark College",
	199:"Liberty University",
	200:"Lincoln University",
	201:"Lindenwood University",
	202:"Lipscomb University",
	203:"Louisiana State University - Baton Rouge",
	204:"Louisiana Tech University",
	205:"Loyola Marymount University",
	206:"Loyola University Chicago",
	207:"Loyola University Maryland",
	208:"Loyola University New Orleans",
	209:"Luther College",
	210:"Macalester College",
	211:"Maine Maritime Academy",
	212:"Manhattan College",
	213:"Marietta College",
	214:"Marist College",
	215:"Marquette University",
	216:"Maryville University of St. Louis",
	217:"Massachusetts Institute of Technology",
	218:"Massachusetts Maritime Academy",
	219:"Mercer University",
	220:"Messiah College",
	221:"Miami University - Oxford",
	222:"Michigan State University",
	223:"Michigan Technological University",
	224:"Middle Tennessee State University",
	225:"Middlebury College",
	226:"Mills College",
	227:"Millsaps College",
	228:"Milwaukee School of Engineering",
	229:"Mississippi State University",
	230:"Missouri University of Science & Technology",
	231:"Montana State University",
	232:"Montana Tech of the University of Montana",
	233:"Montclair State University",
	234:"Morehouse College",
	235:"Morgan State University",
	236:"Mount Holyoke College",
	237:"Muhlenberg College",
	238:"National Louis University",
	239:"New College of Florida",
	240:"New Jersey Institute of Technology",
	241:"New Mexico State University",
	242:"New School",
	243:"New York University",
	244:"North Carolina A&T State University",
	245:"North Carolina Central University",
	246:"North Carolina State University - Raleigh",
	247:"North Dakota State University",
	248:"Northcentral University",
	249:"Northeastern University",
	250:"Northern Arizona University",
	251:"Northern Illinois University",
	252:"Northwestern College",
	253:"Northwestern University",
	254:"Nova Southeastern University",
	255:"Oakland University",
	256:"Oberlin College",
	257:"Occidental College",
	258:"Ohio Northern University",
	259:"Ohio State University",
	260:"Ohio University",
	261:"Ohio Wesleyan University",
	262:"Oklahoma Baptist University",
	263:"Oklahoma State University",
	264:"Old Dominion University",
	265:"Oregon Institute of Technology",
	266:"Oregon State University",
	267:"Pace University",
	268:"Pennsylvania State University - University Park",
	269:"Pepperdine University",
	270:"Pitzer College",
	271:"Pomona College",
	272:"Portland State University",
	273:"Prairie View A&M University",
	274:"Pratt Institute",
	275:"Presbyterian College",
	276:"Princeton University",
	277:"Principia College",
	278:"Providence College",
	279:"Purdue University",
	280:"Quinnipiac University",
	281:"Reed College",
	282:"Regent University",
	283:"Rensselaer Polytechnic Institute",
	284:"Rhode Island School of Design",
	285:"Rhodes College",
	286:"Rice University",
	287:"Ripon College",
	288:"Robert Morris University",
	289:"Rochester Institute of Technology",
	290:"Rocky Mountain College",
	291:"Rollins College",
	292:"Rose-Hulman Institute of Technology",
	293:"Rutgers University - New Brunswick",
	294:"Rutgers University - Newark",
	295:"SUNY - Binghamton University",
	296:"SUNY - College of Environmental Science and Forestry",
	297:"SUNY - Geneseo",
	298:"SUNY - Polytechnic Institute",
	299:"SUNY - Stony Brook University",
	300:"SUNY - University at Albany",
	301:"SUNY - University at Buffalo",
	302:"Saint Louis University",
	303:"Sam Houston State University",
	304:"Samford University",
	305:"San Diego State University",
	306:"San Francisco State University",
	307:"San Jose State University",
	308:"Santa Clara University",
	309:"Sarah Lawrence College",
	310:"Savannah College of Art and Design",
	311:"School of the Art Institute of Chicago",
	312:"Scripps College",
	313:"Seattle Pacific University",
	314:"Seattle University",
	315:"Seton Hall University",
	316:"Sewanee: The University of the South",
	317:"Shenandoah University",
	318:"Simmons College",
	319:"Skidmore College",
	320:"Smith College",
	321:"Soka University of America",
	322:"South Dakota State University",
	323:"Southern Illinois University - Carbondale",
	324:"Southern Methodist University",
	325:"Southwestern University",
	326:"Spalding University",
	327:"Spelman College",
	328:"St. Anselm College",
	329:"St. Francis College",
	330:"St. John Fisher College",
	331:"St. John's College - Annapolis",
	332:"St. John's College - Santa Fe",
	333:"St. John's University",
	334:"St. Joseph's University",
	335:"St. Lawrence University",
	336:"St. Mary's College",
	337:"St. Mary's College of California",
	338:"St. Mary's College of Maryland",
	339:"St. Michael's College",
	340:"St. Olaf College",
	341:"Stanford University",
	342:"Stetson University",
	343:"Stevens Institute of Technology",
	344:"Stonehill College",
	345:"Suffolk University",
	346:"Swarthmore College",
	347:"Syracuse University",
	348:"Taylor University",
	349:"Temple University",
	350:"Tennessee State University",
	351:"Tennessee Technological University",
	352:"Texas A&M University - College Station",
	353:"Texas A&M University - Commerce",
	354:"Texas A&M University - Corpus Christi",
	355:"Texas A&M University - Kingsville",
	356:"Texas Christian University",
	357:"Texas Lutheran University",
	358:"Texas Southern University",
	359:"Texas State University",
	360:"Texas Tech University",
	361:"Texas Woman's University",
	362:"The Citadel",
	363:"Thomas Aquinas College",
	364:"Tougaloo College",
	365:"Transylvania University",
	366:"Trevecca Nazarene University",
	367:"Trinity College",
	368:"Trinity International University",
	369:"Trinity University",
	370:"Truman State University",
	371:"Tufts University",
	372:"Tulane University",
	373:"Tuskegee University",
	374:"Union College",
	375:"Union University",
	376:"United States Air Force Academy",
	377:"United States Coast Guard Academy",
	378:"United States Merchant Marine Academy",
	379:"United States Military Academy",
	380:"United States Naval Academy",
	381:"University of Akron",
	382:"University of Alabama",
	383:"University of Alabama - Birmingham",
	384:"University of Alabama - Huntsville",
	385:"University of Alaska - Fairbanks",
	386:"University of Arizona",
	387:"University of Arkansas",
	388:"University of Arkansas - Little Rock",
	389:"University of California - Berkeley",
	390:"University of California - Davis",
	391:"University of California - Irvine",
	392:"University of California - Los Angeles",
	393:"University of California - Merced",
	394:"University of California - Riverside",
	395:"University of California - San Diego",
	396:"University of California - Santa Barbara",
	397:"University of California - Santa Cruz",
	398:"University of Central Florida",
	399:"University of Chicago",
	400:"University of Cincinnati",
	401:"University of Colorado - Boulder",
	402:"University of Colorado - Denver",
	403:"University of Connecticut",
	404:"University of Dayton",
	405:"University of Delaware",
	406:"University of Denver",
	407:"University of Evansville",
	408:"University of Florida",
	409:"University of Georgia",
	410:"University of Hartford",
	411:"University of Hawaii - Manoa",
	412:"University of Houston",
	413:"University of Idaho",
	414:"University of Illinois - Chicago",
	415:"University of Illinois - Urbana-Champaign",
	416:"University of Iowa",
	417:"University of Kansas",
	418:"University of Kentucky",
	419:"University of La Verne",
	420:"University of Louisiana - Lafayette",
	421:"University of Louisiana - Monroe",
	422:"University of Louisville",
	423:"University of Maine",
	424:"University of Maine - Farmington",
	425:"University of Maryland - Baltimore County",
	426:"University of Maryland - College Park",
	427:"University of Maryland - Eastern Shore",
	428:"University of Massachusetts - Amherst",
	429:"University of Massachusetts - Boston",
	430:"University of Massachusetts - Dartmouth",
	431:"University of Massachusetts - Lowell",
	432:"University of Memphis",
	433:"University of Miami",
	434:"University of Michigan - Ann Arbor",
	435:"University of Minnesota - Twin Cities",
	436:"University of Mississippi",
	437:"University of Missouri",
	438:"University of Missouri - Kansas City",
	439:"University of Missouri - St. Louis",
	440:"University of Mobile",
	441:"University of Montana",
	442:"University of Montana - Western",
	443:"University of Mount Union",
	444:"University of Nebraska - Lincoln",
	445:"University of Nebraska - Omaha",
	446:"University of Nevada - Las Vegas",
	447:"University of Nevada - Reno",
	448:"University of New Hampshire",
	449:"University of New Mexico",
	450:"University of New Orleans",
	451:"University of North Carolina - Chapel Hill",
	452:"University of North Carolina - Charlotte",
	453:"University of North Carolina - Greensboro",
	454:"University of North Dakota",
	455:"University of North Texas",
	456:"University of Northern Colorado",
	457:"University of Notre Dame",
	458:"University of Oklahoma",
	459:"University of Oregon",
	460:"University of Pennsylvania",
	461:"University of Pittsburgh",
	462:"University of Portland",
	463:"University of Puget Sound",
	464:"University of Rhode Island",
	465:"University of Richmond",
	466:"University of Rochester",
	467:"University of San Diego",
	468:"University of San Francisco",
	469:"University of Scranton",
	470:"University of South Alabama",
	471:"University of South Carolina",
	472:"University of South Carolina - Aiken",
	473:"University of South Carolina - Upstate",
	474:"University of South Dakota",
	475:"University of South Florida",
	476:"University of Southern California",
	477:"University of Southern Mississippi",
	478:"University of St. Thomas",
	479:"University of Tennessee",
	480:"University of Texas - Arlington",
	481:"University of Texas - Austin",
	482:"University of Texas - Dallas",
	483:"University of Texas - El Paso",
	484:"University of Texas - San Antonio",
	485:"University of Toledo",
	486:"University of Tulsa",
	487:"University of Utah",
	488:"University of Vermont",
	489:"University of Virginia",
	490:"University of Washington",
	491:"University of West Florida",
	492:"University of West Georgia",
	493:"University of Wisconsin - Madison",
	494:"University of Wisconsin - Milwaukee",
	495:"University of Wyoming",
	496:"University of the Cumberlands",
	497:"University of the Ozarks",
	498:"University of the Pacific",
	499:"Ursinus College",
	500:"Utah State University",
	501:"Valdosta State University",
	502:"Valparaiso University",
	503:"Vanderbilt University",
	504:"Vassar College",
	505:"Vaughn College of Aeronautics and Technology",
	506:"Villanova University",
	507:"Virginia Commonwealth University",
	508:"Virginia Military Institute",
	509:"Virginia Tech",
	510:"Wabash College",
	511:"Wake Forest University",
	512:"Warner Pacific College",
	513:"Washington College",
	514:"Washington State University",
	515:"Washington University in St. Louis",
	516:"Washington and Jefferson College",
	517:"Washington and Lee University",
	518:"Wayne State University",
	519:"Wellesley College",
	520:"Wesleyan University",
	521:"West Virginia University",
	522:"Western Michigan University",
	523:"Westminster College",
	524:"Westmont College",
	525:"Wheaton College",
	526:"Whitman College",
	527:"Whitworth University",
	528:"Wichita State University",
	529:"Widener University",
	530:"Willamette University",
	531:"Williams College",
	532:"Wilmington University",
	533:"Wofford College",
	534:"Worcester Polytechnic Institute",
	535:"Wright State University",
	536:"Xavier University",
	537:"Xavier University of Louisiana",
	538:"Yale University",
	539:"Yeshiva University"
}